baseURL: "https://bussch.github.io/"
title: Christopher Buss
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 

params:
    description: "I am a PhD. Candidate in Computer Science at Oregon State University. My research focuses reducing the manual effort involved in data preperation tasks."
    author: Christopher Buss
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Christopher Buss (He / Him)
          subtitle: "I am a a PhD student in the School of Electrical Engineering and Computer Science at Oregon State University. I'm interested in how AI can be used to reduce the manual effort required in data integration tasks, particularly for practical instances where training data is rare (or altogether non-existent!). Prior to OSU, I worked at a small software company, performing data processing jobs. I'm originally from Wisconsin and received a double-major in computer science and English at UW-Parkside in Kenosha, WI. 
          **I am on the academic job market for Fall 2025 positions.**"
          imageUrl: "christopherbuss.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Scholarly Work
              url: papers/
            - name: Courses Taught
              url: courses/
#            - name: Data
#              url: data/
#            - name: Tags
#              url: tags/
#            - name: Archive
#              url: archive/

    socialIcons:
        - name: CV
          url: christopherbuss_CV.pdf
        - name: Email
          url: mailto:bussch@oregonstate.edu
#        - name: Zoom
#          url: https://www.zoom.us/my/igelfeld
#        - name: Location
#          url: location/
#        - name: Office Hours
#          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=XG7v6AUAAAAJ&hl=en&authuser=1
        - name: GitHub
          url: https://github.com/bussch
#        - name: Substack
#          url: https://pmichaillat.substack.com
#        - name: YouTube
#          url: https://www.youtube.com/@alexandermccallsmithoffici9000
#        - name: Twitter
#          url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Christopher Buss"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2